import IEmployeeInformation from '../../models/IEmployeeInformation';

export const EmployeeInformation: IEmployeeInformation[] = [
  {
    userPrincipalName: 'mbatecok0@domain.com',
    birthday: '11/12/2017',
    emergencyContacts: 'Jamal P. Duffy',
    rewardPoints: 24,
    hobbies: 'Renaissance Faire, Archery',
    music: 'Country',
    interests: 'Hacking',
    food: 'seafood, soups',
    blogs: 'Borland, Cakewalk',
    facebook: '/Donec',
    twitter: '@augue',
    linkedIn: '/vitae,',
    officeCubicle: '275',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'lfilipczak1@domain.com',
    birthday: '01/21/2018',
    emergencyContacts: 'Sharon J. Hudson',
    rewardPoints: 19,
    hobbies: 'Boardgames',
    music: 'Country, Cumbia',
    interests: 'Entertainment',
    food: 'sandwiches',
    blogs: 'Adobe',
    facebook: '/sit',
    twitter: '@Aliquam',
    linkedIn: '/auctor.',
    officeCubicle: '617',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'fdoerr2@domain.com',
    birthday: '06/26/2017',
    emergencyContacts: 'Bruce M. Mccoy',
    rewardPoints: 20,
    hobbies: 'Collecting Swords',
    music: 'Country, Classic',
    interests: 'Lifestyle, Games, Books',
    food: 'salads, pies',
    blogs: 'Lavasoft',
    facebook: '/faucibus.',
    twitter: '@diam',
    linkedIn: '/mauris',
    officeCubicle: '557',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'epovey3@domain.com',
    birthday: '10/31/2016',
    emergencyContacts: 'Kareem J. Armstrong',
    rewardPoints: 14,
    hobbies: 'Cake Decorating',
    music: 'Reggae, Classic',
    interests: 'Books, Technology',
    food: 'pasta',
    blogs: 'Cakewalk, Lycos, Finale',
    facebook: '/et',
    twitter: '@dictum.',
    linkedIn: '/purus',
    officeCubicle: '644',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'mwillowby4@domain.com',
    birthday: '10/08/2017',
    emergencyContacts: 'Georgia J. Russo',
    rewardPoints: 42,
    hobbies: 'Boardgames',
    music: 'Rock-Pop',
    interests: 'Games',
    food: 'pasta, stews',
    blogs: 'Quora',
    facebook: '/dolor.',
    twitter: '@id,',
    linkedIn: '/aliquam',
    officeCubicle: '394',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'bbriggs5@domain.com',
    birthday: '12/25/2016',
    emergencyContacts: 'Steven Z. Kent',
    rewardPoints: 80,
    hobbies: 'Boardgames',
    music: 'Salsa, Classic, Jaz',
    interests: 'News, Music, Politics',
    food: 'desserts, seafood, noodles',
    blogs: 'Quora',
    facebook: '/Mauris',
    twitter: '@lacinia',
    linkedIn: '/imperdiet',
    officeCubicle: '375',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'clinnell6@domain.com',
    birthday: '05/15/2018',
    emergencyContacts: 'Aaron U. Tyler',
    rewardPoints: 74,
    hobbies: 'Stamp Collecting, Watching sporting events',
    music: 'Country',
    interests: 'Hacking',
    food: 'pies, pasta',
    blogs: 'Quora',
    facebook: '/mollis',
    twitter: '@elementum,',
    linkedIn: '/pharetra',
    officeCubicle: '617',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'mleipelt7@domain.com',
    birthday: '09/25/2017',
    emergencyContacts: 'Lee W. Fulton',
    rewardPoints: 8,
    hobbies: 'Stamp Collecting, Fishing',
    music: 'Pop, Cumbia, Reggae',
    interests: 'Hacking',
    food: 'soups',
    blogs: 'Macromedia',
    facebook: '/Vestibulum',
    twitter: '@tincidunt',
    linkedIn: '/scelerisque',
    officeCubicle: '709',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'tbellamy8@domain.com',
    birthday: '04/13/2018',
    emergencyContacts: 'Indigo A. Adkins',
    rewardPoints: 19,
    hobbies: 'Videogames',
    music: 'Rock-Pop',
    interests: 'Business, Technology',
    food: 'pies, salads',
    blogs: 'Borland, Apple Systems, Adobe',
    facebook: '/id',
    twitter: '@lacus.',
    linkedIn: '/nibh.',
    officeCubicle: '689',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'sexroll9@domain.com',
    birthday: '02/25/2018',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Vaughan T. Fulton',
    rewardPoints: 64,
    hobbies: 'Impersonations',
    music: 'Rap, Country',
    interests: 'Business, Books',
    food: 'Tacos',
    blogs: 'Quora',
    facebook: '/eu,',
    twitter: '@lacus.',
    linkedIn: '/Ut',
    officeCubicle: '708',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'gmcellena@domain.com',
    birthday: '10/06/2017',
    vehicule: 'Toyota RAV4 Darkgrey 2008',
    emergencyContacts: 'Juliet W. Marquez',
    rewardPoints: 37,
    hobbies: 'Building Dollhouses',
    music: 'Classic, Blues',
    interests: 'Sports, News, Games',
    food: 'noodles, cereals',
    blogs: 'Chami, Finale, Borland',
    facebook: '/Sed',
    twitter: '@amet,',
    linkedIn: '/imperdiet',
    officeCubicle: '784',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'locriganb@domain.com',
    birthday: '04/15/2017',
    vehicule: 'Toyota RAV4 Darkgrey 2008',
    emergencyContacts: 'Demetrius W. Lyons',
    rewardPoints: 44,
    hobbies: 'Warhammer',
    music: 'Rock-Pop',
    interests: 'Technology, Business',
    food: 'Tacos',
    blogs: 'Microsoft, Chami, Sibelius',
    facebook: '/mauris',
    twitter: '@litora',
    linkedIn: '/elit.',
    officeCubicle: '613',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'ifontec@domain.com',
    birthday: '06/06/2018',
    vehicule: 'Toyota RAV4 Darkgrey 2008',
    emergencyContacts: 'Plato F. Williams',
    rewardPoints: 8,
    hobbies: 'Pottery',
    music: 'Jaz, Heavy Metal',
    interests: 'Food, Games, Technology',
    food: 'Tacos',
    blogs: 'Lavasoft',
    facebook: '/adipiscing',
    twitter: '@turpis.',
    linkedIn: '/habitant',
    officeCubicle: '172',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'demmanuelid@domain.com',
    birthday: '12/02/2016',
    vehicule: '',
    emergencyContacts: 'Herman A. Britt',
    rewardPoints: 43,
    hobbies: 'Videogames',
    music: 'Salsa, Pop, Jaz',
    interests: 'Sports',
    food: 'pies',
    blogs: 'Apple Systems, Macromedia, Chami',
    facebook: '/nunc',
    twitter: '@lectus.',
    linkedIn: '/lacinia',
    officeCubicle: '709',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'cebbitte@domain.com',
    birthday: '05/30/2018',
    vehicule: 'Nissan Tsuru Blue 2014',
    emergencyContacts: 'Jerome Q. Mcclain',
    rewardPoints: 38,
    hobbies: 'Video Games, Go Kart Racing, Renaissance Faire',
    music: 'Rock-Pop',
    interests: 'Entertainment',
    food: 'cereals',
    blogs: 'Quora',
    facebook: '/sed',
    twitter: '@dignissim',
    linkedIn: '/luctus',
    officeCubicle: '903',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'ggrimsdalef@domain.com',
    birthday: '02/01/2018',
    vehicule: 'Nissan Tsuru Blue 2014',
    emergencyContacts: 'Todd T. Mckay',
    rewardPoints: 37,
    hobbies: 'Meditation, Camping, Sleeping',
    music: 'Rock-Pop',
    interests: 'Business, Music, News',
    food: 'desserts, sandwiches',
    blogs: 'Apple Systems',
    facebook: '/ante',
    twitter: '@metus',
    linkedIn: '/pede,',
    officeCubicle: '120',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'urablg@domain.com',
    birthday: '05/16/2017',
    vehicule: 'Toyota RAV4 Darkgrey 2008',
    emergencyContacts: 'Tyrone W. Kelly',
    rewardPoints: 52,
    hobbies: 'Camping, Video Games, Scrapbooking',
    music: 'Blues, Country, Rap',
    interests: 'Technology, News, Games',
    food: 'cereals, salads, pies',
    blogs: 'Macromedia',
    facebook: '/magna',
    twitter: '@ut',
    linkedIn: '/risus.',
    officeCubicle: '708',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'cwhaleyh@domain.com',
    birthday: '06/24/2017',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Cairo R. Britt',
    rewardPoints: 31,
    hobbies: 'Video Games, Sand Castles',
    music: 'Rock, Salsa, Jaz',
    interests: 'Entertainment',
    food: 'desserts, pasta, seafood',
    blogs: 'Yahoo, Finale, Lavasoft',
    facebook: '/massa.',
    twitter: '@magna.',
    linkedIn: '/rhoncus',
    officeCubicle: '415',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'tjurgenseni@domain.com',
    birthday: '10/26/2016',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Carter S. Hansen',
    rewardPoints: 95,
    hobbies: 'Building Dollhouses, Pottery',
    music: 'Rap',
    interests: 'Sports, News',
    food: 'soups, cereals, sandwiches',
    blogs: 'Apple Systems, Borland, Altavista',
    facebook: '/et,',
    twitter: '@auctor',
    linkedIn: '/ultrices',
    officeCubicle: '906',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'hbubeerj@domain.com',
    birthday: '09/18/2016',
    vehicule: 'Nissan Tsuru Blue 2014',
    emergencyContacts: 'Quynn K. Forbes',
    rewardPoints: 89,
    hobbies: 'Go Kart Racing, Video Games, Impersonations',
    music: 'Rock-Pop',
    interests: 'Hacking',
    food: 'cereals, salads',
    blogs: 'Quora',
    facebook: '/non,',
    twitter: '@Nunc',
    linkedIn: '/Maecenas',
    officeCubicle: '331',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'wfaseyk@domain.com',
    birthday: '02/25/2018',
    vehicule: '',
    emergencyContacts: 'Winter H. Roberts',
    rewardPoints: 13,
    hobbies: 'Warhammer, Building Dollhouses',
    music: 'Salsa, Pop',
    interests: 'Politics, Food',
    food: 'pasta, salads, stews',
    blogs: 'Yahoo, Finale, Lycos',
    facebook: '/eros',
    twitter: '@euismod',
    linkedIn: '/justo',
    officeCubicle: '706',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'zgaunterl@domain.com',
    birthday: '10/08/2016',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Owen F. Strickland',
    rewardPoints: 49,
    hobbies: 'Stamp Collecting',
    music: 'Classic',
    interests: 'Hacking',
    food: 'pies',
    blogs: 'Quora',
    facebook: '/enim',
    twitter: '@tristique',
    linkedIn: '/sodales',
    officeCubicle: '121',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'ltrenfieldm@domain.com',
    birthday: '04/17/2017',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Cara I. Ortiz',
    rewardPoints: 81,
    hobbies: 'Renaissance Faire, Sleeping, Scrapbooking',
    music: 'Rock-Pop',
    interests: 'News',
    food: 'noodles',
    blogs: 'Microsoft',
    facebook: '/lobortis',
    twitter: '@consectetuer',
    linkedIn: '/arcu.',
    officeCubicle: '635',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'sbluchern@domain.com',
    birthday: '12/31/2017',
    vehicule: 'Toyota RAV4 Darkgrey 2008',
    emergencyContacts: 'Julie C. Hunter',
    rewardPoints: 71,
    hobbies: 'Impersonations, Pottery',
    music: 'Classic, Pop, Heavy Metal',
    interests: 'Lifestyle, Food',
    food: 'seafood',
    blogs: 'Chami, Apple Systems, Adobe',
    facebook: '/enim,',
    twitter: '@sed',
    linkedIn: '/nec',
    officeCubicle: '398',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'cwhannelo@domain.com',
    birthday: '01/25/2017',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Nichole H. Dudley',
    rewardPoints: 48,
    hobbies: 'Videogames',
    music: 'Salsa, Cumbia',
    interests: 'Games, Lifestyle, Art',
    food: 'pasta',
    blogs: 'Finale, Lavasoft, Apple Systems',
    facebook: '/eu',
    twitter: '@convallis',
    linkedIn: '/lorem',
    officeCubicle: '477',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'guttleyp@domain.com',
    birthday: '08/08/2017',
    vehicule: 'Toyota RAV4 Darkgrey 2008',
    emergencyContacts: 'Joel L. Case',
    rewardPoints: 31,
    hobbies: 'Meditation, Video Games',
    music: 'Jaz, Blues',
    interests: 'Sports',
    food: 'Tacos',
    blogs: 'Lycos, Lavasoft',
    facebook: '/eleifend',
    twitter: '@aliquam',
    linkedIn: '/massa',
    officeCubicle: '754',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'ckeetonq@domain.com',
    birthday: '08/18/2017',
    vehicule: 'Nissan Tsuru Blue 2014',
    emergencyContacts: 'Zane H. Kirk',
    rewardPoints: 73,
    hobbies: 'Cake Decorating, Renaissance Faire',
    music: 'Reggae',
    interests: 'Sports',
    food: 'Tacos',
    blogs: 'Chami, Finale, Yahoo',
    facebook: '/enim',
    twitter: '@hendrerit',
    linkedIn: '/ultricies',
    officeCubicle: '463',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'mraymentr@domain.com',
    birthday: '06/01/2018',
    vehicule: 'Nissan Tsuru Blue 2014',
    emergencyContacts: 'Ira Z. Burris',
    rewardPoints: 84,
    hobbies: 'Camping, Boating',
    music: 'Rock-Pop',
    interests: 'Music, Entertainment, Art',
    food: 'cereals',
    blogs: 'Cakewalk',
    facebook: '/eget,',
    twitter: '@Phasellus',
    linkedIn: '/imperdiet',
    officeCubicle: '606',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'nnolis@domain.com',
    birthday: '12/06/2016',
    vehicule: 'Nissan Tsuru Blue 2014',
    emergencyContacts: 'Ira H. Green',
    rewardPoints: 38,
    hobbies: 'Collecting Swords, Collecting Antiques, Camping',
    music: 'Jaz, Blues, Reggae',
    interests: 'Hacking',
    food: 'salads',
    blogs: 'Quora',
    facebook: '/Vivamus',
    twitter: '@lorem,',
    linkedIn: '/magna.',
    officeCubicle: '339',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'dgrushint@domain.com',
    birthday: '04/14/2017',
    vehicule: '',
    emergencyContacts: 'Kelsie H. Olson',
    rewardPoints: 7,
    hobbies: 'Renaissance Faire, Collecting Swords',
    music: 'Blues, Cumbia, Jaz',
    interests: 'Books, Entertainment',
    food: 'soups, cereals',
    blogs: 'Macromedia',
    facebook: '/aliquet',
    twitter: '@vitae,',
    linkedIn: '/nisi',
    officeCubicle: '913',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'njarlmannu@domain.com',
    birthday: '09/23/2016',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Elliott K. Salinas',
    rewardPoints: 5,
    hobbies: 'Videogames',
    music: 'Rock-Pop',
    interests: 'Games',
    food: 'desserts, stews',
    blogs: 'Quora',
    facebook: '/metus',
    twitter: '@Nunc',
    linkedIn: '/tempor,',
    officeCubicle: '610',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'fgerleitv@domain.com',
    birthday: '03/10/2017',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Zelenia B. Farley',
    rewardPoints: 64,
    hobbies: 'Pottery',
    music: 'Rap',
    interests: 'Food',
    food: 'cereals, stews',
    blogs: 'Quora',
    facebook: '/Proin',
    twitter: '@pulvinar',
    linkedIn: '/Duis',
    officeCubicle: '708',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'tbroodw@domain.com',
    birthday: '08/16/2017',
    vehicule: '',
    emergencyContacts: 'Colorado P. Guerrero',
    rewardPoints: 62,
    hobbies: 'Cake Decorating, Video Games, Meditation',
    music: 'Rap, Pop, Heavy Metal',
    interests: 'Hacking',
    food: 'cereals, sandwiches',
    blogs: 'Quora',
    facebook: '/Sed',
    twitter: '@natoque',
    linkedIn: '/pellentesque',
    officeCubicle: '773',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'gmartinsonx@domain.com',
    birthday: '06/22/2017',
    vehicule: 'Nissan Tsuru Blue 2014',
    emergencyContacts: 'Linda K. Oliver',
    rewardPoints: 96,
    hobbies: 'Renaissance Faire',
    music: 'Pop',
    interests: 'Sports',
    food: 'noodles, sandwiches',
    blogs: 'Adobe, Altavista',
    facebook: '/euismod',
    twitter: '@a,',
    linkedIn: '/id',
    officeCubicle: '806',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'ashewringy@domain.com',
    birthday: '11/24/2017',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Ferdinand J. Moreno',
    rewardPoints: 69,
    hobbies: 'Videogames',
    music: 'Rap',
    interests: 'News, Books',
    food: 'soups, sandwiches',
    blogs: 'Macromedia',
    facebook: '/fermentum',
    twitter: '@leo.',
    linkedIn: '/vehicula.',
    officeCubicle: '801',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'jwillockz@domain.com',
    birthday: '08/06/2017',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Aquila O. Whitaker',
    rewardPoints: 34,
    hobbies: 'Butterfly Watching, Cake Decorating',
    music: 'Pop, Heavy Metal',
    interests: 'Lifestyle, Art',
    food: 'cereals',
    blogs: 'Quora',
    facebook: '/ut',
    twitter: '@Cras',
    linkedIn: '/mi',
    officeCubicle: '194',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'bpeters10@domain.com',
    birthday: '08/13/2017',
    vehicule: 'Ford Focus White 2017',
    emergencyContacts: 'Zia Q. Conrad',
    rewardPoints: 70,
    hobbies: 'Fishing, Sleeping, Calligraphy',
    music: 'Heavy Metal, Country, Rap',
    interests: 'Games',
    food: 'desserts, seafood, pies',
    blogs: 'Quora',
    facebook: '/montes,',
    twitter: '@Aliquam',
    linkedIn: '/consectetuer',
    officeCubicle: '960',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'jormerod11@domain.com',
    birthday: '05/12/2018',
    vehicule: 'Toyota RAV4 Darkgrey 2008',
    emergencyContacts: 'John X. Strickland',
    rewardPoints: 100,
    hobbies: 'Meditation, Butterfly Watching, Calligraphy',
    music: 'Heavy Metal, Country, Blues',
    interests: 'News',
    food: 'pasta, pies',
    blogs: 'Finale, Apple Systems, Lycos',
    facebook: '/convallis',
    twitter: '@lectus',
    linkedIn: '/Class',
    officeCubicle: '657',
    isHomeOffice: false,
  },
  {
    userPrincipalName: 'cpottle12@domain.com',
    birthday: '02/16/2017',
    vehicule: 'Toyota RAV4 Darkgrey 2008',
    emergencyContacts: 'Kaitlin Q. Briggs',
    rewardPoints: 75,
    hobbies: 'Go Kart Racing',
    music: 'Pop, Rock, Jaz',
    interests: 'Entertainment, News, Technology',
    food: 'seafood, desserts',
    blogs: 'Microsoft',
    facebook: '/vulputate,',
    twitter: '@aliquet',
    linkedIn: '/dui',
    officeCubicle: '665',
    isHomeOffice: true,
  },
  {
    userPrincipalName: 'bkiefer13@domain.com',
    birthday: '11/16/2016',
    vehicule: 'Toyota RAV4 Darkgrey 2008',
    emergencyContacts: 'Brody W. Heath',
    rewardPoints: 54,
    hobbies: 'Sleeping, Pottery, Butterfly Watching',
    music: 'Classic, Jaz',
    interests: 'Art, Games',
    food: 'soups, seafood',
    blogs: 'Quora',
    facebook: '/tempor',
    twitter: '@magna.',
    linkedIn: '/Suspendisse',
    officeCubicle: '266',
    isHomeOffice: false,
  },
];
