import IPerformanceSkills from '../../models/IPerformanceSkills';

export const PerformanceSkills: IPerformanceSkills[] = [
  {
    id: 1,
    userPrincipalName: 'cpottle12@domain.com',
    technicalKnowledge: 1,
    teamwork: 0,
    meetingDeadlines: 1,
    problemSolving: 0,
    leadership: 1,
    management: 0,
  },
  {
    id: 2,
    userPrincipalName: 'tbroodw@domain.com',
    technicalKnowledge: 2,
    teamwork: 2,
    meetingDeadlines: 1,
    problemSolving: 1,
    leadership: 1,
    management: 1,
  },
  {
    id: 3,
    userPrincipalName: 'clinnell6@domain.com',
    technicalKnowledge: 2,
    teamwork: 2,
    meetingDeadlines: 2,
    problemSolving: 3,
    leadership: 2,
    management: 3,
  },
  {
    id: 4,
    userPrincipalName: 'urablg@domain.com',
    technicalKnowledge: 3,
    teamwork: 3,
    meetingDeadlines: 3,
    problemSolving: 3,
    leadership: 4,
    management: 4,
  },
  {
    id: 5,
    userPrincipalName: 'bbriggs5@domain.com',
    technicalKnowledge: 4,
    teamwork: 4,
    meetingDeadlines: 4,
    problemSolving: 4,
    leadership: 5,
    management: 5,
  },
  {
    id: 6,
    userPrincipalName: 'njarlmannu@domain.com',
    technicalKnowledge: 5,
    teamwork: 5,
    meetingDeadlines: 5,
    problemSolving: 5,
    leadership: 6,
    management: 6,
  },
  {
    id: 7,
    userPrincipalName: 'tbellamy8@domain.com',
    technicalKnowledge: 9,
    teamwork: 9,
    meetingDeadlines: 9,
    problemSolving: 9,
    leadership: 10,
    management: 10,
  },
  {
    id: 8,
    userPrincipalName: 'cwhannelo@domain.com',
    technicalKnowledge: 7,
    teamwork: 7,
    meetingDeadlines: 7,
    problemSolving: 7,
    leadership: 8,
    management: 8,
  },
  {
    id: 9,
    userPrincipalName: 'urablg@domain.com',
    technicalKnowledge: 3,
    teamwork: 4,
    meetingDeadlines: 3,
    problemSolving: 3,
    leadership: 3,
    management: 4,
  },
  {
    id: 10,
    userPrincipalName: 'ltrenfieldm@domain.com',
    technicalKnowledge: 9,
    teamwork: 9,
    meetingDeadlines: 9,
    problemSolving: 9,
    leadership: 10,
    management: 10,
  },
  {
    id: 11,
    userPrincipalName: 'guttleyp@domain.com',
    technicalKnowledge: 10,
    teamwork: 10,
    meetingDeadlines: 10,
    problemSolving: 10,
    leadership: 9,
    management: 9,
  },
  {
    id: 12,
    userPrincipalName: 'bbriggs5@domain.com',
    technicalKnowledge: 5,
    teamwork: 3,
    meetingDeadlines: 5,
    problemSolving: 3,
    leadership: 4,
    management: 4,
  },
  {
    id: 13,
    userPrincipalName: 'nnolis@domain.com',
    technicalKnowledge: 3,
    teamwork: 3,
    meetingDeadlines: 4,
    problemSolving: 2,
    leadership: 3,
    management: 3,
  },
  {
    id: 14,
    userPrincipalName: 'urablg@domain.com',
    technicalKnowledge: 3,
    teamwork: 3,
    meetingDeadlines: 3,
    problemSolving: 4,
    leadership: 4,
    management: 3,
  },
  {
    id: 15,
    userPrincipalName: 'mleipelt7@domain.com',
    technicalKnowledge: 7,
    teamwork: 7,
    meetingDeadlines: 7,
    problemSolving: 7,
    leadership: 8,
    management: 7,
  },
  {
    id: 16,
    userPrincipalName: 'ifontec@domain.com',
    technicalKnowledge: 8,
    teamwork: 8,
    meetingDeadlines: 8,
    problemSolving: 7,
    leadership: 8,
    management: 8,
  },
  {
    id: 17,
    userPrincipalName: 'tbellamy8@domain.com',
    technicalKnowledge: 9,
    teamwork: 9,
    meetingDeadlines: 9,
    problemSolving: 8,
    leadership: 9,
    management: 9,
  },
  {
    id: 18,
    userPrincipalName: 'gmcellena@domain.com',
    technicalKnowledge: 1,
    teamwork: 4,
    meetingDeadlines: 3,
    problemSolving: 6,
    leadership: 7,
    management: 6,
  },
  {
    id: 19,
    userPrincipalName: 'cwhannelo@domain.com',
    technicalKnowledge: 5,
    teamwork: 10,
    meetingDeadlines: 10,
    problemSolving: 10,
    leadership: 2,
    management: 3,
  },
  {
    id: 20,
    userPrincipalName: 'hbubeerj@domain.com',
    technicalKnowledge: 4,
    teamwork: 3,
    meetingDeadlines: 3,
    problemSolving: 3,
    leadership: 3,
    management: 3,
  },
  {
    id: 21,
    userPrincipalName: 'sbluchern@domain.com',
    technicalKnowledge: 1,
    teamwork: 9,
    meetingDeadlines: 9,
    problemSolving: 3,
    leadership: 6,
    management: 4,
  },
  {
    id: 22,
    userPrincipalName: 'ltrenfieldm@domain.com',
    technicalKnowledge: 4,
    teamwork: 7,
    meetingDeadlines: 5,
    problemSolving: 2,
    leadership: 6,
    management: 4,
  },
  {
    id: 23,
    userPrincipalName: 'mbatecok0@domain.com',
    technicalKnowledge: 10,
    teamwork: 2,
    meetingDeadlines: 1,
    problemSolving: 5,
    leadership: 8,
    management: 2,
  },
  {
    id: 24,
    userPrincipalName: 'ifontec@domain.com',
    technicalKnowledge: 6,
    teamwork: 8,
    meetingDeadlines: 8,
    problemSolving: 7,
    leadership: 8,
    management: 8,
  },
  {
    id: 25,
    userPrincipalName: 'jormerod11@domain.com',
    technicalKnowledge: 6,
    teamwork: 2,
    meetingDeadlines: 8,
    problemSolving: 1,
    leadership: 9,
    management: 3,
  },
  {
    id: 26,
    userPrincipalName: 'ltrenfieldm@domain.com',
    technicalKnowledge: 9,
    teamwork: 2,
    meetingDeadlines: 7,
    problemSolving: 9,
    leadership: 9,
    management: 5,
  },
  {
    id: 27,
    userPrincipalName: 'sbluchern@domain.com',
    technicalKnowledge: 9,
    teamwork: 9,
    meetingDeadlines: 7,
    problemSolving: 4,
    leadership: 4,
    management: 3,
  },
  {
    id: 28,
    userPrincipalName: 'jwillockz@domain.com',
    technicalKnowledge: 5,
    teamwork: 2,
    meetingDeadlines: 4,
    problemSolving: 2,
    leadership: 8,
    management: 5,
  },
  {
    id: 29,
    userPrincipalName: 'sbluchern@domain.com',
    technicalKnowledge: 4,
    teamwork: 6,
    meetingDeadlines: 1,
    problemSolving: 7,
    leadership: 9,
    management: 5,
  },
  {
    id: 30,
    userPrincipalName: 'zgaunterl@domain.com',
    technicalKnowledge: 6,
    teamwork: 2,
    meetingDeadlines: 5,
    problemSolving: 3,
    leadership: 2,
    management: 3,
  },
  {
    id: 31,
    userPrincipalName: 'mleipelt7@domain.com',
    technicalKnowledge: 7,
    teamwork: 7,
    meetingDeadlines: 7,
    problemSolving: 7,
    leadership: 9,
    management: 7,
  },
  {
    id: 32,
    userPrincipalName: 'tbroodw@domain.com',
    technicalKnowledge: 2,
    teamwork: 2,
    meetingDeadlines: 1,
    problemSolving: 1,
    leadership: 2,
    management: 2,
  },
  {
    id: 33,
    userPrincipalName: 'clinnell6@domain.com',
    technicalKnowledge: 2,
    teamwork: 2,
    meetingDeadlines: 2,
    problemSolving: 3,
    leadership: 3,
    management: 2,
  },
  {
    id: 34,
    userPrincipalName: 'guttleyp@domain.com',
    technicalKnowledge: 8,
    teamwork: 2,
    meetingDeadlines: 2,
    problemSolving: 7,
    leadership: 2,
    management: 1,
  },
  {
    id: 35,
    userPrincipalName: 'bbriggs5@domain.com',
    technicalKnowledge: 3,
    teamwork: 5,
    meetingDeadlines: 4,
    problemSolving: 4,
    leadership: 5,
    management: 4,
  },
  {
    id: 36,
    userPrincipalName: 'locriganb@domain.com',
    technicalKnowledge: 6,
    teamwork: 3,
    meetingDeadlines: 2,
    problemSolving: 9,
    leadership: 4,
    management: 7,
  },
  {
    id: 37,
    userPrincipalName: 'bbriggs5@domain.com',
    technicalKnowledge: 4,
    teamwork: 4,
    meetingDeadlines: 4,
    problemSolving: 5,
    leadership: 4,
    management: 4,
  },
  {
    id: 38,
    userPrincipalName: 'tjurgenseni@domain.com',
    technicalKnowledge: 2,
    teamwork: 6,
    meetingDeadlines: 6,
    problemSolving: 1,
    leadership: 4,
    management: 7,
  },
  {
    id: 39,
    userPrincipalName: 'ifontec@domain.com',
    technicalKnowledge: 10,
    teamwork: 8,
    meetingDeadlines: 7,
    problemSolving: 8,
    leadership: 8,
    management: 8,
  },
  {
    id: 40,
    userPrincipalName: 'cwhaleyh@domain.com',
    technicalKnowledge: 2,
    teamwork: 5,
    meetingDeadlines: 9,
    problemSolving: 7,
    leadership: 7,
    management: 1,
  },
  {
    id: 41,
    userPrincipalName: 'bkiefer13@domain.com',
    technicalKnowledge: 7,
    teamwork: 2,
    meetingDeadlines: 1,
    problemSolving: 2,
    leadership: 2,
    management: 2,
  },
  {
    id: 42,
    userPrincipalName: 'ckeetonq@domain.com',
    technicalKnowledge: 8,
    teamwork: 10,
    meetingDeadlines: 5,
    problemSolving: 9,
    leadership: 8,
    management: 10,
  },
  {
    id: 43,
    userPrincipalName: 'njarlmannu@domain.com',
    technicalKnowledge: 4,
    teamwork: 5,
    meetingDeadlines: 5,
    problemSolving: 4,
    leadership: 1,
    management: 6,
  },
  {
    id: 44,
    userPrincipalName: 'hbubeerj@domain.com',
    technicalKnowledge: 3,
    teamwork: 3,
    meetingDeadlines: 3,
    problemSolving: 2,
    leadership: 3,
    management: 4,
  },
  {
    id: 45,
    userPrincipalName: 'mbatecok0@domain.com',
    technicalKnowledge: 4,
    teamwork: 10,
    meetingDeadlines: 8,
    problemSolving: 9,
    leadership: 3,
    management: 2,
  },
  {
    id: 46,
    userPrincipalName: 'nnolis@domain.com',
    technicalKnowledge: 2,
    teamwork: 2,
    meetingDeadlines: 3,
    problemSolving: 3,
    leadership: 4,
    management: 3,
  },
  {
    id: 47,
    userPrincipalName: 'mbatecok0@domain.com',
    technicalKnowledge: 1,
    teamwork: 7,
    meetingDeadlines: 1,
    problemSolving: 7,
    leadership: 2,
    management: 9,
  },
  {
    id: 48,
    userPrincipalName: 'tbroodw@domain.com',
    technicalKnowledge: 1,
    teamwork: 2,
    meetingDeadlines: 2,
    problemSolving: 2,
    leadership: 1,
    management: 1,
  },
  {
    id: 49,
    userPrincipalName: 'mwillowby4@domain.com',
    technicalKnowledge: 3,
    teamwork: 9,
    meetingDeadlines: 10,
    problemSolving: 10,
    leadership: 7,
    management: 6,
  },
  {
    id: 50,
    userPrincipalName: 'dgrushint@domain.com',
    technicalKnowledge: 4,
    teamwork: 2,
    meetingDeadlines: 8,
    problemSolving: 8,
    leadership: 9,
    management: 6,
  },
  {
    id: 51,
    userPrincipalName: 'bbriggs5@domain.com',
    technicalKnowledge: 3,
    teamwork: 4,
    meetingDeadlines: 3,
    problemSolving: 4,
    leadership: 4,
    management: 5,
  },
  {
    id: 52,
    userPrincipalName: 'dgrushint@domain.com',
    technicalKnowledge: 7,
    teamwork: 9,
    meetingDeadlines: 4,
    problemSolving: 1,
    leadership: 6,
    management: 8,
  },
  {
    id: 53,
    userPrincipalName: 'sbluchern@domain.com',
    technicalKnowledge: 3,
    teamwork: 4,
    meetingDeadlines: 2,
    problemSolving: 6,
    leadership: 10,
    management: 7,
  },
  {
    id: 54,
    userPrincipalName: 'demmanuelid@domain.com',
    technicalKnowledge: 6,
    teamwork: 8,
    meetingDeadlines: 7,
    problemSolving: 7,
    leadership: 10,
    management: 2,
  },
  {
    id: 55,
    userPrincipalName: 'bkiefer13@domain.com',
    technicalKnowledge: 5,
    teamwork: 4,
    meetingDeadlines: 2,
    problemSolving: 5,
    leadership: 9,
    management: 8,
  },
  {
    id: 56,
    userPrincipalName: 'tbellamy8@domain.com',
    technicalKnowledge: 9,
    teamwork: 7,
    meetingDeadlines: 9,
    problemSolving: 10,
    leadership: 9,
    management: 9,
  },
  {
    id: 57,
    userPrincipalName: 'tbroodw@domain.com',
    technicalKnowledge: 0,
    teamwork: 0,
    meetingDeadlines: 1,
    problemSolving: 1,
    leadership: 1,
    management: 2,
  },
  {
    id: 58,
    userPrincipalName: 'bbriggs5@domain.com',
    technicalKnowledge: 4,
    teamwork: 4,
    meetingDeadlines: 4,
    problemSolving: 4,
    leadership: 5,
    management: 5,
  },
  {
    id: 59,
    userPrincipalName: 'fdoerr2@domain.com',
    technicalKnowledge: 10,
    teamwork: 10,
    meetingDeadlines: 10,
    problemSolving: 10,
    leadership: 10,
    management: 10,
  },
  {
    id: 60,
    userPrincipalName: 'clinnell6@domain.com',
    technicalKnowledge: 2,
    teamwork: 2,
    meetingDeadlines: 2,
    problemSolving: 2,
    leadership: 2,
    management: 2,
  },
  {
    id: 61,
    userPrincipalName: 'fdoerr2@domain.com',
    technicalKnowledge: 9,
    teamwork: 10,
    meetingDeadlines: 10,
    problemSolving: 9,
    leadership: 10,
    management: 10,
  },
  {
    id: 62,
    userPrincipalName: 'sbluchern@domain.com',
    technicalKnowledge: 1,
    teamwork: 6,
    meetingDeadlines: 2,
    problemSolving: 9,
    leadership: 9,
    management: 9,
  },
  {
    id: 63,
    userPrincipalName: 'mraymentr@domain.com',
    technicalKnowledge: 7,
    teamwork: 10,
    meetingDeadlines: 7,
    problemSolving: 8,
    leadership: 10,
    management: 7,
  },
  {
    id: 64,
    userPrincipalName: 'ggrimsdalef@domain.com',
    technicalKnowledge: 1,
    teamwork: 5,
    meetingDeadlines: 4,
    problemSolving: 10,
    leadership: 9,
    management: 9,
  },
  {
    id: 65,
    userPrincipalName: 'ifontec@domain.com',
    technicalKnowledge: 8,
    teamwork: 8,
    meetingDeadlines: 7,
    problemSolving: 8,
    leadership: 8,
    management: 8,
  },
  {
    id: 66,
    userPrincipalName: 'epovey3@domain.com',
    technicalKnowledge: 5,
    teamwork: 9,
    meetingDeadlines: 6,
    problemSolving: 4,
    leadership: 3,
    management: 6,
  },
  {
    id: 67,
    userPrincipalName: 'demmanuelid@domain.com',
    technicalKnowledge: 8,
    teamwork: 6,
    meetingDeadlines: 7,
    problemSolving: 8,
    leadership: 6,
    management: 6,
  },
  {
    id: 68,
    userPrincipalName: 'fgerleitv@domain.com',
    technicalKnowledge: 5,
    teamwork: 10,
    meetingDeadlines: 9,
    problemSolving: 10,
    leadership: 10,
    management: 1,
  },
  {
    id: 69,
    userPrincipalName: 'urablg@domain.com',
    technicalKnowledge: 4,
    teamwork: 3,
    meetingDeadlines: 3,
    problemSolving: 4,
    leadership: 3,
    management: 4,
  },
  {
    id: 70,
    userPrincipalName: 'zgaunterl@domain.com',
    technicalKnowledge: 1,
    teamwork: 3,
    meetingDeadlines: 1,
    problemSolving: 2,
    leadership: 2,
    management: 5,
  },
  {
    id: 71,
    userPrincipalName: 'clinnell6@domain.com',
    technicalKnowledge: 2,
    teamwork: 3,
    meetingDeadlines: 2,
    problemSolving: 3,
    leadership: 2,
    management: 3,
  },
  {
    id: 72,
    userPrincipalName: 'gmartinsonx@domain.com',
    technicalKnowledge: 7,
    teamwork: 3,
    meetingDeadlines: 9,
    problemSolving: 6,
    leadership: 4,
    management: 2,
  },
  {
    id: 73,
    userPrincipalName: 'wfaseyk@domain.com',
    technicalKnowledge: 9,
    teamwork: 7,
    meetingDeadlines: 4,
    problemSolving: 3,
    leadership: 10,
    management: 7,
  },
  {
    id: 74,
    userPrincipalName: 'demmanuelid@domain.com',
    technicalKnowledge: 10,
    teamwork: 10,
    meetingDeadlines: 10,
    problemSolving: 10,
    leadership: 4,
    management: 9,
  },
  {
    id: 75,
    userPrincipalName: 'fgerleitv@domain.com',
    technicalKnowledge: 3,
    teamwork: 8,
    meetingDeadlines: 4,
    problemSolving: 5,
    leadership: 9,
    management: 6,
  },
  {
    id: 76,
    userPrincipalName: 'sbluchern@domain.com',
    technicalKnowledge: 7,
    teamwork: 3,
    meetingDeadlines: 3,
    problemSolving: 6,
    leadership: 4,
    management: 7,
  },
  {
    id: 77,
    userPrincipalName: 'epovey3@domain.com',
    technicalKnowledge: 8,
    teamwork: 7,
    meetingDeadlines: 6,
    problemSolving: 4,
    leadership: 5,
    management: 9,
  },
  {
    id: 78,
    userPrincipalName: 'ifontec@domain.com',
    technicalKnowledge: 8,
    teamwork: 9,
    meetingDeadlines: 7,
    problemSolving: 8,
    leadership: 8,
    management: 8,
  },
  {
    id: 79,
    userPrincipalName: 'clinnell6@domain.com',
    technicalKnowledge: 3,
    teamwork: 2,
    meetingDeadlines: 2,
    problemSolving: 1,
    leadership: 3,
    management: 2,
  },
  {
    id: 80,
    userPrincipalName: 'demmanuelid@domain.com',
    technicalKnowledge: 8,
    teamwork: 8,
    meetingDeadlines: 7,
    problemSolving: 2,
    leadership: 9,
    management: 8,
  },
  {
    id: 81,
    userPrincipalName: 'mwillowby4@domain.com',
    technicalKnowledge: 1,
    teamwork: 8,
    meetingDeadlines: 4,
    problemSolving: 4,
    leadership: 7,
    management: 1,
  },
  {
    id: 82,
    userPrincipalName: 'sexroll9@domain.com',
    technicalKnowledge: 2,
    teamwork: 6,
    meetingDeadlines: 2,
    problemSolving: 8,
    leadership: 9,
    management: 4,
  },
  {
    id: 83,
    userPrincipalName: 'ckeetonq@domain.com',
    technicalKnowledge: 9,
    teamwork: 1,
    meetingDeadlines: 4,
    problemSolving: 6,
    leadership: 3,
    management: 4,
  },
  {
    id: 84,
    userPrincipalName: 'cwhannelo@domain.com',
    technicalKnowledge: 2,
    teamwork: 8,
    meetingDeadlines: 10,
    problemSolving: 7,
    leadership: 3,
    management: 8,
  },
  {
    id: 85,
    userPrincipalName: 'epovey3@domain.com',
    technicalKnowledge: 7,
    teamwork: 10,
    meetingDeadlines: 5,
    problemSolving: 6,
    leadership: 6,
    management: 9,
  },
  {
    id: 86,
    userPrincipalName: 'locriganb@domain.com',
    technicalKnowledge: 6,
    teamwork: 10,
    meetingDeadlines: 3,
    problemSolving: 4,
    leadership: 5,
    management: 10,
  },
  {
    id: 87,
    userPrincipalName: 'epovey3@domain.com',
    technicalKnowledge: 8,
    teamwork: 3,
    meetingDeadlines: 10,
    problemSolving: 4,
    leadership: 2,
    management: 3,
  },
  {
    id: 88,
    userPrincipalName: 'cwhaleyh@domain.com',
    technicalKnowledge: 6,
    teamwork: 5,
    meetingDeadlines: 4,
    problemSolving: 4,
    leadership: 3,
    management: 10,
  },
  {
    id: 89,
    userPrincipalName: 'bbriggs5@domain.com',
    technicalKnowledge: 4,
    teamwork: 5,
    meetingDeadlines: 5,
    problemSolving: 4,
    leadership: 4,
    management: 3,
  },
  {
    id: 90,
    userPrincipalName: 'ckeetonq@domain.com',
    technicalKnowledge: 7,
    teamwork: 5,
    meetingDeadlines: 3,
    problemSolving: 2,
    leadership: 10,
    management: 5,
  },
  {
    id: 91,
    userPrincipalName: 'wfaseyk@domain.com',
    technicalKnowledge: 8,
    teamwork: 2,
    meetingDeadlines: 3,
    problemSolving: 7,
    leadership: 7,
    management: 10,
  },
  {
    id: 92,
    userPrincipalName: 'ifontec@domain.com',
    technicalKnowledge: 8,
    teamwork: 9,
    meetingDeadlines: 8,
    problemSolving: 8,
    leadership: 9,
    management: 8,
  },
  {
    id: 93,
    userPrincipalName: 'cpottle12@domain.com',
    technicalKnowledge: 1,
    teamwork: 1,
    meetingDeadlines: 1,
    problemSolving: 1,
    leadership: 0,
    management: 0,
  },
  {
    id: 94,
    userPrincipalName: 'fdoerr2@domain.com',
    technicalKnowledge: 10,
    teamwork: 9,
    meetingDeadlines: 10,
    problemSolving: 9,
    leadership: 10,
    management: 10,
  },
  {
    id: 95,
    userPrincipalName: 'urablg@domain.com',
    technicalKnowledge: 4,
    teamwork: 2,
    meetingDeadlines: 2,
    problemSolving: 3,
    leadership: 3,
    management: 3,
  },
  {
    id: 96,
    userPrincipalName: 'cwhannelo@domain.com',
    technicalKnowledge: 7,
    teamwork: 6,
    meetingDeadlines: 3,
    problemSolving: 7,
    leadership: 10,
    management: 9,
  },
  {
    id: 97,
    userPrincipalName: 'tjurgenseni@domain.com',
    technicalKnowledge: 7,
    teamwork: 10,
    meetingDeadlines: 9,
    problemSolving: 4,
    leadership: 7,
    management: 7,
  },
  {
    id: 98,
    userPrincipalName: 'mwillowby4@domain.com',
    technicalKnowledge: 10,
    teamwork: 9,
    meetingDeadlines: 9,
    problemSolving: 3,
    leadership: 4,
    management: 3,
  },
  {
    id: 99,
    userPrincipalName: 'tbellamy8@domain.com',
    technicalKnowledge: 9,
    teamwork: 9,
    meetingDeadlines: 9,
    problemSolving: 8,
    leadership: 9,
    management: 7,
  },
  {
    id: 100,
    userPrincipalName: 'fdoerr2@domain.com',
    technicalKnowledge: 9,
    teamwork: 10,
    meetingDeadlines: 10,
    problemSolving: 10,
    leadership: 9,
    management: 10,
  },
];
